version: '2'
services:
    fseconomy2-app:
        image: fseconomy2
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://fseconomy2-postgresql:5432/fseconomy2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://fseconomy2-elasticsearch:9200
        ports:
            - 8080:8080
    fseconomy2-postgresql:
        extends:
            file: postgresql.yml
            service: fseconomy2-postgresql
    fseconomy2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: fseconomy2-elasticsearch
