version: '2'
services:
    fseconomy2-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/fseconomy2/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=fseconomy2
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
